language: node_js
node_js: node
os: osx
cache:
  directories:
    - node_modules
services: postgresql
before_script:
  - sudo apt-get -qq update # qq for less output
  - createuser root
  - createdb codesling-travis
  - yarn db:setup:rest-server
install:
  - yarn
  - yarn buildEnv
  - yarn setup:rest-server
  - yarn setup:socket-server
  - yarn setup:services/coderunner-service
script:
  - yarn start & # starts all back-end servers
  - sleep 10
  - zip -r latest *
  - mkdir -p dpl_cd_upload-api
  - mv latest.zip dpl_cd_upload-api/latest.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    skip_cleanup: true # prevents resetting and deleting all changes
    on: &2
      repo: KevinDavidBrian/codesling.io-api
    bucket: kdb-legacy-api
    # region: us-west-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kdb-legacy-api
    key: latest.zip
    bundle_type: zip
    application: kdb-legacy-api
    deployment_group: kdbDeploymentGroupe
    region: us-west-1b
    on: *2
